#!/usr/bin/perl
use Mojolicious::Lite;
use Data::Dumper;

get '/' => sub {
        my $self = shift;
        $self->render_later;
	my $delay = Mojo::IOLoop->delay(sub {
		my $delay = shift;
		warn Data::Dumper::Dumper(\@_);
		$self->render(json=>\@_);
	});
	for my $sleep (qw/2 1 5 1/) {
		my $end = $delay->begin(0);
		$self->ua->get("http://localhost:3002/$sleep" => sub {
			my ($ua, $tx) = @_;
			$end->(join("-=-", $tx->res->code, $sleep));
		});
	}
	my $end = $delay->begin(0);
	$end->(scalar localtime);
	$delay->wait unless Mojo::IOLoop->is_running;
	warn scalar localtime;
};

get '/:sleep' => {sleep => 0} => sub {
	my $self = shift;
	my $sleep = $self->param('sleep');
	$self->render_later; # Without this, slowsleep will be automatically rendered
	Mojo::IOLoop->timer($sleep => sub {
		return $self->render(json=>{
			ok => Mojo::JSON->true,
			sleep => $sleep,
		});
	});
};

app->start;
